mrblib/itamae/recipe_context.rb, mrblib/itamae/resource/group.rb, mrblib/itamae/resource_executor/group.rb
```ruby
group "example_group" do
group_name "example" # optional
gid 4998 # optional
end
```
cf. https://github.com/itamae-kitchen/itamae/blob/master/lib/itamae/resource/group.rb
=> add group resource

mrblib/itamae/recipe_context.rb, mrblib/itamae/resource/user.rb, mrblib/itamae/resource_executor/user.rb
```ruby
user "example" do
username "example" # optional
gid "example_group" # optional
home "/home/example" # optional
password "xxxxx" # optional
system_user false # optional
uid 1111 # optional
shell "/bin/bash" # optional
create_home false # optional
end
```
cf. https://github.com/itamae-kitchen/itamae/blob/master/lib/itamae/resource/user.rb
=> add user resource

.travis.yml, Rakefile, benchmark/create.rb, benchmark/delete.rb, mrbgem.rake, mrblib/mitamae/resource_executor/directory.rb, mrblib/mitamae/resource_executor/file.rb
file creation: 3:21 → 2:47
no operation: 4:21 → 4:16
file deletion: 0.50 → 0:34
=> Fast file executor

mrblib/mitamae/recipe_context.rb, mrblib/mitamae/recipe_runner.rb, spec/integration/include_recipe_spec.rb, spec/integration/included_spec.rb, spec/recipes/default.rb, spec/recipes/include_counter.rb, spec/recipes/include_recipe.rb, spec/recipes/included.rb, spec/recipes/nested_recipe.rb
Avoid including the same recipes even if they are nested.
=> Duplication resolver

PLUGINS.md, README.md, mrblib/mitamae/cli/local.rb, mrblib/mitamae/plugin.rb, mrblib/mitamae/recipe_context.rb
Both https://github.com/k0kubun/itamae-plugin-resource-cask and https://github.com/k0kubun/itamae-plugin-recipe-rbenv should work in plugins/.
=> Recipe plugin

.gitignore, .gitmodules, Rakefile
Managing mruby to clone the fixed revision with `--depth 1`.
=> Use latest mruby

.gitignore, .gitmodules, .travis.yml, README.md, Rakefile
It allows building mitamae without ~Ruby~ Rake.
=> Use mruby/minirake as a build tool

mrblib/mitamae/recipe.rb
Resolve #28 
I haven't found the root cause, but this workaround works for me.
=> Add workaround for SEGV at MItamae::Recipe#inspect

mrblib/mitamae/inline_backends/file_backend.rb
I've added an inline backend example for run_command case.
=> Inline get_file_mode

mrbgem.rake, mrblib/mitamae/inline_backends/file_backend.rb
I've created a small mrbgem for this patch.
https://github.com/eagletmt/mruby-etc
=> Inline get_file_owner_user and get_file_owner_group

mrblib/mitamae/resource_executor/file.rb
I'm currently focusing on speeding up dry-run mode.
I have inlined most part of file operations run in dry-run mode.
FYI: I've sent a pull-request to add `File.chown` . It is necessary to inline `change_file_mode` .
https://github.com/iij/mruby-io/pull/70
=> Inline file operations

mrblib/mitamae/resource_executor/file.rb
Copy from the source file directly without creating temporary files.
=> Skip unnecessary file copy in remote_file resource

mrblib/mitamae/resource_executor/file.rb
Reverts k0kubun/mitamae#41
It changes the source file's attributes unexpectedly. I have to seek another way to reduce unneccessary file copies.
ref. #47
=> Revert "Skip unnecessary file copy in remote_file resource"

mrblib/mitamae/resource/execute.rb, spec/integration/execute_spec.rb, spec/recipes/execute.rb
This makes it possible to execute commands without going through the
shell.
=> Allow array command

build_config.rb, mrblib/mitamae/resource_executor/link.rb, spec/integration/link_spec.rb, spec/recipes/link.rb
follow this change: https://github.com/itamae-kitchen/itamae/pull/229
TODO: set `checksum_hash` of mruby-specinfra after this p-r https://github.com/k0kubun/mruby-specinfra/pull/3 is merged.
=> [WIP] Support force link to a direcotory

build_config.rb
This is for better debugging: https://github.com/iij/mruby-io/commit/6836f424c5ff95d0114a426010b22254804bc9a3
whole diff: https://github.com/iij/mruby-io/compare/86d58a2d3727f556e6e6ce10d170b6170911a263...6836f424c5ff95d0114a426010b22254804bc9a3
(IMO there're rooms to upgrade other mrbgems but I'm interested only in that change)
=> upgrade mruby-io

CHANGELOG.md, mrblib/mitamae/version.rb
@k0kubun Could you release a new version for #66 ? (or can I make a new release?)
=> Version 1.5.2

build_config.rb
=> Use latest iij/mruby-socket.

mrbgem.rake, mrblib/mitamae/resource_executor/http_request.rb, spec/integration/http_request_spec.rb, spec/recipes/http_request.rb, spec/recipes/http_request_without_curl.rb
=> Change http_request backend to curl(1)

mrblib/mitamae/recipe_executor.rb, spec/recipes/notifies.rb
mitamae has not inherited this behavior: https://github.com/itamae-kitchen/itamae/blob/v1.10.2/lib/itamae/recipe.rb#L75
=> Deduplicate delayed notifications

mrblib/mitamae/resource/http_request.rb, mrblib/mitamae/resource_executor/http_request.rb
https://github.com/itamae-kitchen/mitamae/pull/79#issuecomment-473690071
=> http_request compatible with itamae

mrbgem.rake, mrblib/mitamae/node.rb, spec/recipes/node.rb
Origin: https://github.com/itamae-kitchen/itamae/commit/b46d446779723fe044e3616a30a09a928cb53582
Travis CI: https://travis-ci.org/takumin/mitamae/builds/558430865
=> Add Node#validate!

mrblib/mitamae/resource/http_request.rb, mrblib/mitamae/resource_executor/http_request.rb, spec/integration/http_request_spec.rb, spec/recipes/http_request_client_error.rb, spec/recipes/http_request_redirect_limit.rb, spec/recipes/http_request_server_error.rb, spec/recipes/http_request_unknown_error.rb
- Remove check_error attribute:
https://github.com/itamae-kitchen/mitamae/commit/27ad78fbb69707514a1a65a410a594be23ec595d
- Check HTTP status code:
https://github.com/itamae-kitchen/itamae/commit/28b359d6c7a4487e1562396dfefc31c1fafd42bd
=> Changed http_request resource to Itamae compatible

.github/workflows/docker.yml, build_config.rb
=> Build aarch64-darwin binary in CI

mrblib/mitamae/resource/file.rb, mrblib/mitamae/resource/http_request.rb, mrblib/mitamae/resource/remote_file.rb, mrblib/mitamae/resource/template.rb, mrblib/mitamae/resource_executor/file.rb
=> Support sensitive attribute

README.md
=> Use execute

.github/workflows/build.yml
Verify whether the mitamae binary is installed correctly.
Forked GitHub Repository Commit:
https://github.com/takumin/mitamae/commit/6eea393522eb102527805be48d08dd2616bb70b8
Forked GitHub Actions Workflows:
https://github.com/takumin/mitamae/actions/runs/14703390547
Forked GitHub Action Checksum Workflow:
https://github.com/takumin/mitamae/actions/runs/14703390547/job/41257997863
=> Generate SHA256 Checksums
