- mrbgem.rake
- mrblib/itamae/cli/local.rb
- mrblib/itamae/plugin.rb
- mrblib/itamae/recipe_context.rb
- mrblib/itamae/resource/base.rb
- mrblib/itamae/resource_executor.rb
- Resource plugin must be `Itamae::Plugin::Resource::*` and inherit `Itamae::Resource::Base`
- Its executor must be `Itamae::Plugin::ResourceExecutor::*`
- mrbgem repositories under `plugins/` are automatically loaded
- Add them as git submodule or copy them
- They should have code under `mrblib/`
- Example
- Simple case: https://github.com/k0kubun/itamae-plugin-resource-cask/pull/4
- Concept for complex case: https://github.com/k0kubun/itamae-plugin-resource-portage/pull/1
> Resource plugin

- mrblib/mitamae/node.rb
- spec/integration/node_spec.rb
- spec/recipes/node.rb
- spec/recipes/templates/tmp/node_assign.erb
- spec/recipes/templates/tmp/node_merge.erb
Fixed the following problem.
```rb
node[:a] #=> nil
node[:b] #=> nil
node[:a] = 'hello'
node.merge!(b: 'world')
node[:a] #=> nil
node[:b] #=> nil
```
Thank you for reporting this! @rosylilly
> Fix node object assignment and merging

- .gitmodules
- mrblib/mitamae/resource/base.rb
- mrblib/mitamae/resource_executor/base.rb
- mrblib/mitamae/resource_executor/directory.rb
- mrblib/mitamae/resource_executor/execute.rb
- mrblib/mitamae/resource_executor/file.rb
- mrblib/mitamae/resource_executor/gem_package.rb
- mrblib/mitamae/resource_executor/git.rb
- mrblib/mitamae/resource_executor/group.rb
- mrblib/mitamae/resource_executor/http_request.rb
- mrblib/mitamae/resource_executor/link.rb
- mrblib/mitamae/resource_executor/local_ruby_block.rb
- mrblib/mitamae/resource_executor/package.rb
- mrblib/mitamae/resource_executor/remote_directory.rb
- mrblib/mitamae/resource_executor/service.rb
- mrblib/mitamae/resource_executor/user.rb
Add `pre_action` hook and change the roles of hook methods in resource_executor.
- `set_current_attributes` and `set_desired_attributes` should be pure.
- Because current file resource's `set_desired_attributes` has a destructive operation, `set_current_attributes` depends on that it is called after `set_desired_attributes`. Current `current`/`desired` design fails at that point.
- Destructive operations should be put in `pre_action` hook.
> Add pre_action hook

- mrblib/mitamae/cli/local.rb
- mrblib/mitamae/inline_backend.rb
- mrblib/mitamae/inline_backends/file_backend.rb
- mrblib/mitamae/resource_executor/base.rb
- mrblib/mitamae/runner.rb
It improves performance because it skips `test -d`. External command
invocations are slow operations compared to just calling syscalls in the
same process.
Before
```
% cat test.rb
directory '/tmp/hello' do
owner 'eagletmt'
group 'staff'
mode '755'
end
% mitamae local test.rb -l debug
INFO : Recipe: /home/eagletmt/.ghq/github.com/k0kubun/mitamae/test.rb
DEBUG :   directory[/tmp/hello]
DEBUG :     directory[/tmp/hello] action: create
DEBUG :       (in set_desired_attributes)
DEBUG :       (in set_current_attributes)
DEBUG :       Executing `test -d /tmp/hello`...
DEBUG :         exited with 0
DEBUG :       Executing `stat -c %a /tmp/hello`...
DEBUG :         stdout | 755
DEBUG :         exited with 0
DEBUG :       Executing `stat -c %U /tmp/hello`...
DEBUG : …
```
> Add InlineBackend and run check_file_is_directory with it

- mrblib/mitamae/inline_backends/file_backend.rb
`run_command(:get_file_owner_user, path)` was raising an exception when
the underlying stat command failed. So the inline backends should raise
an exception on error cases.
https://github.com/k0kubun/mitamae/pull/32/files#r91998048
@k0kubun what do you think?
> Let exceptions go up

- mrblib/mitamae/backend.rb
- mrblib/mitamae/resource_executor/git.rb
- mrblib/mitamae/resource_executor/remote_directory.rb
Executing a string command is slow because it needs to launch a shell and it has an overhead of shell startup, shell script parsing, etc. If the `run_command` is called with an array command, it could be executed without a shell.
> Execute commands without shell if possible 

- mrblib/mitamae/resource_executor/base.rb
I'd like to see actions triggered by notifications in dry-run mode.
That behavior is compatible with itamae.
```ruby
execute 'true' do
action :nothing
end
file '/tmp/test.txt' do
notifies :run, 'execute[true]'
end
```
Before
```
% mitamae local test.rb --dry-run
INFO : Recipe: /home/eagletmt/.ghq/github.com/k0kubun/mitamae/test.rb
INFO :   file[/tmp/test.txt] exist will change from 'false' to 'true'
```
After
```
% mitamae local test.rb --dry-run
INFO : Recipe: /home/eagletmt/.ghq/github.com/k0kubun/mitamae/test.rb
INFO :   file[/tmp/test.txt] exist will change from 'false' to 'true'
INFO :   Notifying run to execute resource 'true' (delayed)
INFO :   execute[true] executed will change from 'false' to 'true'
```
> Set updated flag in dry-run mode

- mrblib/mitamae/resource_executor/remote_directory.rb
- spec/integration/remote_directory_spec.rb
remote_direcotry resource crashes in show_defferences because of lack of `@temppath`.
```
% mitamae local -ldebug spec/recipes/remote_directory.rb
INFO : Recipe: /Users/makimoto/.ghq/github.com/k0kubun/mitamae/spec/recipes/remote_directory.rb
DEBUG :   remote_directory[/tmp/remdir]
DEBUG :     remote_directory[/tmp/remdir] action: create
DEBUG :       (in set_desired_attributes)
DEBUG :       (in set_current_attributes)
DEBUG :       (in pre_action)
DEBUG :       (in show_differences)
INFO :       remote_directory[/tmp/remdir] exist will change from 'false' to 'true'
DEBUG :       Executing `cp -r /Users/makimoto/.ghq/github.com/k0kubun/mitamae/spec/recipes/remdir /tmp/remdir`...
DEBUG :         exited with 0
DEBUG :       This resource is updated.
% mitamae …
```
> Fix bug in remote_directory resource when desired directory exists

- mrblib/mitamae/resource_context.rb
- mrblib/mitamae/resource_executor/base.rb
- spec/integration/execute_spec.rb
- spec/recipes/file.rb
It allows inlining only_if/not_if conditions.
Example:
```ruby
execute 'git clone https://github.com/k0kubun/mitamae' do
not_if { FileTest.directory?('mitamae') }
end
```
> Accept callable object as only_if/not_if command

- mrblib/mitamae/resource_executor/service.rb
`action` is set not only from `action` attribute in resource definitions
but from notifications.
```ruby
file '/tmp/hoge.txt' do
content "#{Time.now.to_i}\n"
notifies :reload, 'service[nginx]'
end
service 'nginx'
```
In this example, applying this recipe is expected to reload nginx, but
it isn't because `current.running` isn't initialized. All current
attributes should be initialized regardless of `action` attribute.
> Set all current attributes regardless of action attribute

- mrblib/mitamae/resource/git.rb
- mrblib/mitamae/resource_executor/git.rb
- spec/integration/git_spec.rb
- spec/recipes/git.rb
I used Itamae, but use MItamae now.
Itamae can execute below code.
```ruby
git "/tmp/fake_depth_repo" do
repository "https://github.com/hatappi/fake_depth_repo.git"
depth 1
end
```
ref: https://github.com/itamae-kitchen/itamae/blob/master/lib/itamae/resource/git.rb#L13
But MItamae cannot use this.
I want to use `--depth` option.
For example [neologd/mecab-ipadic-neologd](https://github.com/neologd/mecab-ipadic-neologd) install.
> Support depth attribute to git resource

- docker-compose.yml
v3 is the currently recommended format, but the difference between v2
and v3 doesn't have compatibility impact on mitamae spec.
https://docs.docker.com/compose/compose-file/compose-versioning/
> Migrate docker-compse.yml to v2 format

- mrblib/mitamae/recipe.rb
Show recipe files **on loading**.
By default, mitamae shows recipe files to execute as INFO level, but once the loading fails (e.g. syntax errors, no such file or directory, is a directory, etc.) debugging is not easy:
```
mruby/bin/mitamae local --log-level=debug .
trace:
(snip)
[14] (path to)/mitamae/mrblib/mitamae.rb:2:in Object.__main__
(path to)/mitamae/mruby/build/mrbgems/mruby-io/mrblib/io.rb:175: Is a directory - sysread failed (Errno::EISDIR)
```
It includes no information about filenames.
With this PR, the logs include the file name like:
```
DEBUG : Loading recipe: . # <- filename
```
> show logs for Recipe.load

- mrblib/mitamae/resource_executor/gem_package.rb
- spec/integration/gem_package_spec.rb
- spec/recipes/gem_package.rb
`gem list -l` shows "default: " prefix for default gems since v2.6.3.
https://github.com/rubygems/rubygems/pull/1570
Before
```
% cat test.rb
gem_package 'bigdecimal' do
version '1.3.0'
end
% gem --version
2.6.13
% mruby/build/host/bin/mitamae local test.rb --dry-run
INFO : Recipe: /home/eagletmt/.ghq/github.com/k0kubun/mitamae/test.rb
INFO :   gem_package[bigdecimal] version will change from 'default: 1.3.0' to '1.3.0'
```
After
```
% mruby/build/host/bin/mitamae local test.rb --dry-run
INFO : Recipe: /home/eagletmt/.ghq/github.com/k0kubun/mitamae/test.rb
```
> Strip "default: " prefix from gem versions

- mrbgem.rake
I wanted to use at_exit in local_ruby_block. This is for recipe's convenience, not for mitamae's internal implementation.
> Install mruby-at_exit

- mrblib/mitamae/inline_backends/file_backend.rb
MItamae crashes when the file being manipulated by the `file` resource is owned by a user or a group that does not have their name in the passwd/group database. Itamae does not crash in the same condition (though I don't know it's intended or unintentionally working).
```console
% stat /tmp/test
File: /tmp/test
Size: 0               Blocks: 0          IO Block: 4096   regular empty file
Device: 68h/104d        Inode: 29          Links: 1
Access: (0755/-rwxr-xr-x)  Uid: (12345/ UNKNOWN)   Gid: (12345/ UNKNOWN)
Access: 2019-11-28 14:47:28.672696794 +0000
Modify: 2019-11-28 14:45:31.387417648 +0000
Change: 2019-11-28 14:45:31.387417648 +0000
Birth: -
% cat test.rb
file '/tmp/test' do
owner 'root'
group 'root'
end
% mruby/bin/mitamae local test.rb
INFO : Starting mitamae...
INFO : Recipe: …
```
> Fix crash when file resource handles files with nameless owner

- LICENSE
- build_config.rb
- mrbgem.rake
Related: https://github.com/itamae-kitchen/mitamae/commit/328663bdad3485de88b51546830dff71dc22553a
> Statically link musl-libc for x86 Linux builds

- README.md
This repository is no longer using Travis CI.
So I add GitHub Actions badge
> Migrate to GitHub Actions badge

- mrblib/mitamae/cli.rb
- mrblib/mitamae/cli/local.rb
- mrblib/mitamae/logger.rb
- spec/integration/color_spec.rb
- spec/recipes/color.rb
Added `--color` and `--no-color` options.
I didn't know that I needed to get the results of the execution of mitamae itself, so I just made sure that no exception was raised.
relates #111
> add `--color` option and `--no-color` option

- mrbgem.rake
I'm unsure when mruby-enum-ext was removed from the dependencies (looks like it was a indirect dep), and I noticed methods from enum-ext have disappeared after upgrading my mitamae build.
I believe it is reasonable to bundle mruby-enum-ext as well as other core *-ext mrbgems.
> bundle mruby-enum-ext

- mrblib/mitamae/inline_backends/user_backend.rb
- spec/integration/user_spec.rb
- spec/recipes/user.rb
Currently, mitamae get user information by `Etc.getpwnam()`. That function retrieves data from `/etc/passwd`.
https://www.rubydoc.info/stdlib/etc/Etc.getpwnam
In my environment (Ubuntu 20.04.3), encrypted password is stored in `/etc/shadow`, so `current_password` in user resource returns `'x'` as encrypted password.
There is **no problem to create user and set password** of the user by recipe, but it **falsely detect** that encrypted password differs.
I wrote some tests.
```ruby
itamae3_encrypted_password = '$6$salt$IxDD3jeSOb5eB1CX5LBsqZFVkJdido3OUILO5Ifz5iwMuTS4XMS130MTSuDDl3aCI6WouIL9AjRbLCelDCy.g.'
user 'create itamae3 user with password hash' do
username 'itamae3'
password itamae3_encrypted_password
end
user 'create itamae3 user with password hash again' do
username 'itamae3' …
```
> Get user encrypted password from /etc/shadow

- README.md
- mrblib/mitamae/backend.rb
This adds a new argument to `run_command`, `stream_output: true`, that
will log output lines to the console as they come in. In addition, if
debug logging is enabled, command output will be streamed instead of
being collected and then printed.
> Add support for live streaming command output to the console

- mrblib/mitamae/resource_executor/local_ruby_block.rb
- spec/recipes/local_ruby_block.rb
"local_ruby_block" execute by itamae's ruby process. The process doesn't change its working directory, which is presented by "cwd" attribute.
I think it's the root cause of itamae's issue https://github.com/itamae-kitchen/itamae/issues/353
I made the local_ruby_block code execute inside of Dir.chdir block if cwd attribute was presented to fix it.
This behavior has existed since 2015 (in itamae https://github.com/itamae-kitchen/itamae/pull/146, not mitamae).
There might be a recipe that is dependent on current behavior somewhere.
Although I couldn't find public itamae recipes that use "local_ruby_block" with "cwd", the change has a small impact, I think.
ref https://github.com/itamae-kitchen/itamae/pull/355
@k0kubun how do you think?
> Execute local_ruby_block code inside of chdir-ed block if cwd presented

- spec/integration/host_inventory_spec.rb
block device of host inventory is not empty on version 1.13.1.
failed test: https://github.com/itamae-kitchen/mitamae/runs/7554499967?check_suite_focus=true#step:5:7366
```
1) host_inventory File "/tmp/host_inventory_block_device" content is expected to match /\A{}\z/
Failure/Error: its(:content) { should match(expected) }
expected "{\"loop0\"=>{\"rotational\"=>\"1\", \"removable\"=>\"0\", \"size\"=>\"138880\"}, \"loop1\"=>{\"rotat...300\", \"vendor\"=>\"Msft\", \"rotational\"=>\"1\", \"removable\"=>\"0\", \"size\"=>\"180355072\"}}" to match /\A{}\z/
Diff:
@@ -1 +1 @@
-/\A{}\z/
+"{\"loop0\"=>{\"rotational\"=>\"1\", \"removable\"=>\"0\", \"size\"=>\"138880\"}, \"loop1\"=>{\"rotational\"=>\"1\", \"removable\"=>\"0\", \"size\"=>\"126824\"}, \"loop2\"=>{\"rotational\"=>\"1\", …
```
> fix host inventory spec

- .github/workflows/build.yml
fixes warnings: The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2, goto-bus-stop/setup-zig@v1. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
> bump the actions of GitHub Actions

- spec/integration/http_request_spec.rb
- spec/recipes/http_request.rb
httpbingo.org now checks redirect URLs.
```
% curl 'http://httpbingo.org/redirect-to?url=https%3A%2F%2Fhttpbin.org%2Fget%3Ffrom%3Ditamae'
Forbidden redirect URL. Please be careful with this link.
Allowed redirect destinations:
- example.com
- example.net
- example.org
- httpbingo.org
```
This pull request changes to use allowed URLs
> fix broken integrated tests

- build_config.rb.lock
This pull request contains:
- Support Amazon Linux 2022 https://github.com/mizzy/specinfra/pull/738
- Replace obsolete File.exists? with File.exist? https://github.com/mizzy/specinfra/pull/739
- Add Guix support https://github.com/mizzy/specinfra/pull/740
- add KDE Neon support https://github.com/mizzy/specinfra/pull/742
- Add VyOS Support https://github.com/mizzy/specinfra/pull/743
- Add support for Amazon Linux 2023 https://github.com/mizzy/specinfra/pull/744
https://github.com/mizzy/specinfra/compare/v2.83.4...v2.87.0 https://github.com/itamae-kitchen/mruby-specinfra/compare/2a66b88cf87143b7d0ee8ab28ca3cbd69ad367cf...aa98e3e9aa89f9a305cf0f875bfe76a6fff905e6
> bump specinfra v2.87.0 from v2.83.3

- build_config.rb.lock
This pull request contains:
- [Clear BUNDLER_SETUP env in exec #757](https://github.com/mizzy/specinfra/pull/757)
- [Detect Debian Testing and assign a impossibly high version number #758](https://github.com/mizzy/specinfra/pull/758)
- [feat: Add platform_codename host inventory #759](https://github.com/mizzy/specinfra/pull/759)
List of changes:
- [mizzy/specinfra@v2.91.0...v2.94.0](https://github.com/mizzy/specinfra/compare/v2.91.0...v2.94.0)
- [itamae-kitchen/mruby-specinfra@133975a...d6d0fda](https://github.com/itamae-kitchen/mruby-specinfra/compare/133975a79e968c35ec23bc0dc24b7dd7e79c9d29...d6d0fda00c3f099b346a73a43cda53f03ed32a2e)
> Update mruby-specinfra to 2.94.0

- .github/workflows/build.yml
Sign build artifacts in GitHub Actions workflow to provide verifiable origins for the artifacts.
See also:
- GitHub Artifact Attestations is generally available
- https://github.blog/changelog/2024-06-25-artifact-attestations-is-generally-available/
- GitHub Action: `actions/attest-build-provenance@v2`
- https://github.com/actions/attest-build-provenance
> Generate GitHub Artifact Attestations

- .github/workflows/build.yml
Artifact attestation using `actions/attest-build-provenance` requires appropriate permissions (OIDC token and secrets), which are not available in `pull_request` events for security reasons.
This commit restricts the attestation step to only run on:
- `master` branch
- `build-*` branches
- `tag` refs (`refs/tags/*`)
This ensures provenance attestation is only generated during trusted build contexts.
Related PR:
- https://github.com/itamae-kitchen/mitamae/pull/137
> Limit artifact attestation to push events on trusted refs
